import './globals.css'
import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'

const inter = Outfit({ weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MSK Portfoilo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
